import Navbar from '@/components/Navbar'
import './globals.css'
import { GlobalProvider } from './context/GlobalContext'
import { Toaster } from './Toaster'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="aqua">
      <body className="container mx-auto px-4 h-screen">
        <GlobalProvider>
          <Navbar />
          {children}
        </GlobalProvider>
        <Toaster />
      </body>
    </html>


  )
}
